# Generated by Django 5.1.4 on 2026-08-19 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ls', models.CharField(max_length=50, verbose_name='Лицевой счет')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('area', models.FloatField(verbose_name='Площадь (м2)')),
                ('rate', models.FloatField(verbose_name='Тариф (сом / м2)')),
                ('rate_sum', models.FloatField(editable=False, verbose_name='Сумма по тарифу')),
                ('address', models.TextField(max_length=200, verbose_name='Адрес')),
                ('saldo', models.FloatField(default=0, verbose_name='Сальдо')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('last_payment', models.FloatField(default=0, verbose_name='Последняя оплата')),
                ('last_dept', models.FloatField(default=0, verbose_name='Долг за предыдущий месяц')),
                ('last_prepayment', models.FloatField(default=0, verbose_name='Предоплата за предыдущий месяц')),
                ('current_dept', models.FloatField(default=0, verbose_name='Долг за текущий месяц')),
                ('current_prepayment', models.FloatField(default=0, verbose_name='Предоплата за текущий месяц')),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('calculated_payment', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Абоненты',
                'verbose_name_plural': 'Абоненты',
            },
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, verbose_name='Дата платежа')),
                ('payment', models.FloatField(verbose_name='Сумма платежа')),
                ('ls', models.CharField(default='', max_length=50, verbose_name='Лицевой счет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users_app.usermodel')),
            ],
            options={
                'verbose_name': 'Платежи',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
