# Generated by Django 5.1.4 on 2024-12-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'Абоненты', 'verbose_name_plural': 'Абоненты'},
        ),
    ]
