# Generated by Django 5.1.4 on 2026-08-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='current_dept',
            field=models.FloatField(default=0, verbose_name='Долг на конец периода'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='current_prepayment',
            field=models.FloatField(default=0, verbose_name='Предоплата на конец периода'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_dept',
            field=models.FloatField(default=0, verbose_name='Долг на начало периода'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_payment',
            field=models.FloatField(default=0, verbose_name='Оплачено за период'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_prepayment',
            field=models.FloatField(default=0, verbose_name='Предоплата на начало периода'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='saldo',
            field=models.FloatField(default=0, help_text='Личный остаток абонента: минус — долг, плюс — переплата.', verbose_name='Сальдо'),
        ),
    ]
