# Generated by Django 5.1.4 on 2026-08-19 18:08

from django.db import migrations, models


def seed_period_charge(apps, schema_editor):
    """Существующим абонентам: начислено за период = текущая сумма по тарифу.

    Так вид квитанции сразу после обновления не меняется. Со следующего
    начисления поле начнёт заполняться снимком автоматически.
    """
    UserModel = apps.get_model("users_app", "UserModel")
    UserModel.objects.update(period_charge=models.F("rate_sum"))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_usermodel_current_dept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='period_charge',
            field=models.FloatField(default=0, help_text='Снимок суммы, реально списанной при последнем начислении. Именно она печатается в графе «Начислено».', verbose_name='Начислено за период'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='rate_sum',
            field=models.FloatField(editable=False, verbose_name='Сумма по тарифу (текущая)'),
        ),
        migrations.RunPython(seed_period_charge, noop),
    ]
