# Generated by Django 5.1.4 on 2026-08-20 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_usermodel_period_charge_alter_usermodel_rate_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='apartment',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Квартира'),
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=120, verbose_name='Улица / микрорайон')),
                ('number', models.CharField(max_length=20, verbose_name='Номер дома')),
                ('number_order', models.PositiveIntegerField(default=0, editable=False)),
                ('service_type', models.CharField(default='ТО', help_text='Печатается в последней графе свода.', max_length=20, verbose_name='Вид ком. услуг')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
                'ordering': ('street', 'number_order', 'number'),
                'constraints': [models.UniqueConstraint(fields=('street', 'number'), name='unique_house')],
            },
        ),
        migrations.AddField(
            model_name='usermodel',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='users_app.house', verbose_name='Дом'),
        ),
        migrations.CreateModel(
            name='PeriodSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], verbose_name='Месяц')),
                ('ls', models.CharField(max_length=50, verbose_name='Лицевой счет')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('apartment', models.CharField(blank=True, default='', max_length=20, verbose_name='Квартира')),
                ('area', models.FloatField(default=0, verbose_name='Площадь (м2)')),
                ('rate', models.FloatField(default=0, verbose_name='Тариф (сом / м2)')),
                ('opening_debit', models.FloatField(default=0, verbose_name='Сальдо нач. месяца, дебет')),
                ('opening_credit', models.FloatField(default=0, verbose_name='Сальдо нач. месяца, кредит')),
                ('charged_ku', models.FloatField(default=0, verbose_name='Начислено, КУ')),
                ('charged_fee', models.FloatField(default=0, verbose_name='Начислено, 3%')),
                ('paid_ku', models.FloatField(default=0, verbose_name='Оплачено, КУ')),
                ('paid_fee', models.FloatField(default=0, verbose_name='Оплачено, 3%')),
                ('transfer', models.FloatField(default=0, verbose_name='Перевод')),
                ('penalty', models.FloatField(default=0, verbose_name='Пеня')),
                ('refund', models.FloatField(default=0, verbose_name='Возврат')),
                ('closing_debit', models.FloatField(default=0, verbose_name='Сальдо кон. месяца, дебет')),
                ('closing_credit', models.FloatField(default=0, verbose_name='Сальдо кон. месяца, кредит')),
                ('overdue', models.FloatField(default=0, verbose_name='Просроченная задолженность')),
                ('service_type', models.CharField(default='ТО', max_length=20, verbose_name='Вид ком. услуг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Записано в архив')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='users_app.house', verbose_name='Дом')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='users_app.usermodel', verbose_name='Абонент')),
            ],
            options={
                'verbose_name': 'Архив начислений',
                'verbose_name_plural': 'Архив начислений',
                'ordering': ('-year', '-month', 'address', 'ls'),
                'indexes': [models.Index(fields=['year', 'month'], name='users_app_p_year_fc0c70_idx'), models.Index(fields=['year', 'month', 'house'], name='users_app_p_year_c8e1b5_idx')],
                'constraints': [models.UniqueConstraint(fields=('subscriber', 'year', 'month'), name='unique_snapshot_per_period')],
            },
        ),
    ]
