# Generated by Django 5.1.4 on 2026-08-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_fill_houses_from_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('question', models.CharField(max_length=260, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос и ответ',
                'verbose_name_plural': 'Вопросы и ответы',
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('eyebrow', models.CharField(default='Приветствуем!', max_length=80, verbose_name='Надзаголовок')),
                ('title', models.CharField(max_length=180, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('button_text', models.CharField(default='Заказать звонок', max_length=80, verbose_name='Текст кнопки')),
                ('image', models.ImageField(blank=True, upload_to='site/hero/', verbose_name='Изображение')),
                ('image_path', models.CharField(blank=True, help_text='Используется, если файл не загружен. Допустим путь вида /images/hero/slide.jpg.', max_length=500, verbose_name='Резервный путь изображения')),
            ],
            options={
                'verbose_name': 'Слайд первого экрана',
                'verbose_name_plural': 'Слайды первого экрана',
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='URL-имя')),
                ('title', models.CharField(max_length=220, verbose_name='Название')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('price_label', models.CharField(default='По запросу', max_length=80, verbose_name='Цена')),
                ('category', models.CharField(choices=[('paid', 'Платная услуга'), ('included', 'Входит в обслуживание')], default='paid', max_length=20, verbose_name='Категория')),
                ('image', models.ImageField(blank=True, upload_to='services/', verbose_name='Изображение')),
                ('image_path', models.CharField(blank=True, help_text='Используется, если файл не загружен.', max_length=500, verbose_name='Резервный путь изображения')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показывать на главной')),
                ('legacy_path', models.CharField(blank=True, help_text='Нужен для постоянного редиректа со старой версии сайта.', max_length=320, verbose_name='Старый URL')),
                ('meta_title', models.CharField(blank=True, max_length=180, verbose_name='SEO-заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=320, verbose_name='SEO-описание')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Услуга сайта',
                'verbose_name_plural': 'Услуги сайта',
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='SiteFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('title', models.CharField(max_length=140, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(choices=[('shield-check', 'Щит'), ('file-chart', 'Отчётность'), ('house-heart', 'Дом и комфорт'), ('hard-hat', 'Подрядчики')], default='shield-check', max_length=32, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SiteMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('value', models.CharField(max_length=30, verbose_name='Значение')),
                ('label', models.CharField(max_length=120, verbose_name='Подпись')),
                ('icon', models.CharField(choices=[('building', 'Дом'), ('users', 'Жители'), ('headphones', 'Поддержка'), ('smile', 'Улыбка')], default='building', max_length=32, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Показатель компании',
                'verbose_name_plural': 'Показатели компании',
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='ОсОО «АВЛИ»', max_length=120, verbose_name='Название компании')),
                ('short_name', models.CharField(default='АВЛИ', max_length=40, verbose_name='Короткое название')),
                ('tagline', models.CharField(default='Надёжное управление многоквартирными домами в Бишкеке', max_length=180, verbose_name='Слоган')),
                ('about_title', models.CharField(default='Надёжный партнёр вашего дома', max_length=180, verbose_name='Заголовок блока «О нас»')),
                ('about_text', models.TextField(verbose_name='Текст о компании')),
                ('about_text_secondary', models.TextField(blank=True, verbose_name='Дополнительный текст о компании')),
                ('mission', models.TextField(blank=True, verbose_name='Миссия')),
                ('footer_text', models.TextField(blank=True, verbose_name='Текст в подвале')),
                ('address', models.CharField(max_length=240, verbose_name='Адрес')),
                ('phone_primary', models.CharField(max_length=40, verbose_name='Основной телефон')),
                ('phone_secondary', models.CharField(blank=True, max_length=40, verbose_name='Дополнительный телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Только цифры с кодом страны, например 996225215740.', max_length=30, verbose_name='WhatsApp')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Ссылка на Telegram')),
                ('map_embed_url', models.URLField(blank=True, max_length=1000, verbose_name='Ссылка на карту (embed)')),
                ('seo_title', models.CharField(max_length=180, verbose_name='SEO-заголовок')),
                ('seo_description', models.CharField(max_length=320, verbose_name='SEO-описание')),
                ('og_image', models.ImageField(blank=True, upload_to='site/', verbose_name='Изображение для соцсетей')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('name', models.CharField(max_length=140, verbose_name='Имя')),
                ('role', models.CharField(default='Житель', max_length=80, verbose_name='Подпись')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('initials', models.CharField(blank=True, max_length=8, verbose_name='Инициалы')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, verbose_name='Комментарий')),
                ('page', models.CharField(blank=True, max_length=320, verbose_name='Страница заявки')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Обработана'), ('spam', 'Спам')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Получена')),
            ],
            options={
                'verbose_name': 'Заявка с сайта',
                'verbose_name_plural': 'Заявки с сайта',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='users_app_c_status_79246c_idx')],
            },
        ),
    ]
